force-app/main/default/objects/HealthRecord__c/HealthRecord__c.object-meta.xml
<CustomObject>
    <label>Health Record</label>
    <nameField>
        <displayFormat>HR-{0000}</displayFormat>
        <label>Health Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Health Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HealthRecord__c/fields/Date_and_Time__c.field-meta.xml
<CustomField>
    <fullName>Date_and_Time__c</fullName>
    <label>Date and Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/HealthRecord__c/fields/Evening_BP_Reading_Down__c.field-meta.xml
<CustomField>
    <fullName>Evening_BP_Reading_Down__c</fullName>
    <formula>IF(Phase__c == &quot;Evening&quot;,  BP_Down__c , 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Evening BP Reading Down</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HealthRecord__c/fields/Evening_BP_Reading_Up__c.field-meta.xml
<CustomField>
    <fullName>Evening_BP_Reading_Up__c</fullName>
    <formula>IF(Phase__c == &quot;Evening&quot;,  BP_Up__c  , 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Evening BP Reading Up</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HealthRecord__c/fields/Evening_Medicine__c.field-meta.xml
<CustomField>
    <fullName>Evening_Medicine__c</fullName>
    <formula>IF(Phase__c == &quot;Evening&quot;, Medicine__c , &quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Evening Medicine</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HealthRecord__c/fields/Evening_Time__c.field-meta.xml
<CustomField>
    <fullName>Evening_Time__c</fullName>
    <formula>IF(Phase__c == &quot;Evening&quot;,  TIMEVALUE( Date_and_Time__c ) , null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Evening Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/HealthRecord__c/fields/Morning_BP_Reading_Down__c.field-meta.xml
<CustomField>
    <fullName>Morning_BP_Reading_Down__c</fullName>
    <formula>IF(Phase__c == &quot;Morning&quot;,  BP_Down__c , 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Morning BP Down</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HealthRecord__c/fields/Morning_BP_Reading_Up__c.field-meta.xml
<CustomField>
    <fullName>Morning_BP_Reading_Up__c</fullName>
    <formula>IF(Phase__c == &quot;Morning&quot;,  BP_Up__c , 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Morning BP Up</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HealthRecord__c/fields/Morning_Medicine__c.field-meta.xml
<CustomField>
    <fullName>Morning_Medicine__c</fullName>
    <formula>IF(Phase__c == &quot;Morning&quot;,  Medicine__c , &quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Morning Medicine</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HealthRecord__c/fields/Morning_Time__c.field-meta.xml
<CustomField>
    <fullName>Morning_Time__c</fullName>
    <formula>IF(Phase__c == &quot;Morning&quot;, TIMEVALUE( Date_and_Time__c ) , null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Morning Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/HealthRecord__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <formula>IF(
    TIMEVALUE(Date_and_Time__c) &lt;  TIMEVALUE(&quot;10:30:00.000&quot;) ,
    &quot;Morning&quot;,
    &quot;Evening&quot;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Phase</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HealthRecord__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <label>User</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alex Brown</fullName>
                <default>true</default>
                <label>Alex Brown</label>
            </value>
            <value>
                <fullName>Robin Pinaka</fullName>
            </value>
            <value>
                <fullName>Aakash Singh</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HealthRecordController.cls
public without sharing class HealthRecordController {
    @AuraEnabled(cacheable=true)
    public static List<HealthRecord__c> getHealthRecords(String selectedUser) {
        System.debug('selectedUser> ' + selectedUser);
        if(selectedUser != null){
            // Query health records based on the selected user (you can add more filters as needed)
            return convertDateIntoUserTZ([SELECT Id, Phase__c, Date_and_Time__c, Morning_Time__c, Morning_BP_Reading_Up__c, Morning_BP_Reading_Down__c, Morning_Medicine__c, Evening_Time__c, Evening_BP_Reading_Up__c, Evening_BP_Reading_Down__c, Evening_Medicine__c
                    FROM HealthRecord__c
                    WHERE User__c = :selectedUser
                    ORDER BY Date_and_Time__c, Morning_Time__c]);
        }else{
            return new List<HealthRecord__c>();
        }
    }

    private static List<HealthRecord__c> convertDateIntoUserTZ(List<HealthRecord__c> healthRecords){
        for(HealthRecord__c healthRecord : healthRecords){
            if(healthRecord.Date_and_Time__c != null){
                TimeZone tz = UserInfo.getTimeZone();
                healthRecord.Date_and_Time__c = convertTZtoGMT(healthRecord.Date_and_Time__c, tz.getID());
            }
        }

        return healthRecords;
    }


    @AuraEnabled(cacheable=true)
    public static List<AllUsersWrapper> getUniqueUsers() {
        Set<String> uniqueUsers = new Set<String>();

        // Query distinct User values from HealthRecord__c
        List<AggregateResult> results = [SELECT User__c FROM HealthRecord__c GROUP BY User__c];

        // Add unique User values to the list
        for (AggregateResult result : results) {
            String userValue = (String)result.get('User__c');
            if (userValue != null) {
                uniqueUsers.add(userValue);
            }
        }

        List<AllUsersWrapper> wrapperList = new List<AllUsersWrapper>();
        for(String user : uniqueUsers){
            AllUsersWrapper wrapper = new AllUsersWrapper();
            wrapper.label = user;
            wrapper.value = user;
            wrapperList.add(wrapper);
        }

        return wrapperList;
    }

    public static Datetime convertGMTtoTZ(Datetime dt, String timeZoneName) {
        return doConversion(dt, timeZoneName, false);
    }

    public static Datetime convertTZtoGMT(Datetime dt, String timeZoneName) {
        return doConversion(dt, timeZoneName, true);
    }

    private static Datetime doConversion(Datetime dt, String timeZoneName, Boolean addOrRemove) {
        Integer multiplier = (addOrRemove ? 1 : -1);
        Integer offsetInMinute = getTimezoneOffsetInMinutes(dt, timeZoneName);
        dt = dt.addMinutes(multiplier * offsetInMinute);
        return dt;
    }

    private static Integer getTimezoneOffsetInMinutes(Datetime dt, String timeZoneName) {
        TimeZone storeTimeZone = TimeZone.getTimeZone(timeZoneName);
        Integer offsetInMinute = storeTimeZone.getOffset(dt) / (60 * 1000);
        return offsetInMinute;
    }

    public class AllUsersWrapper{
        @AuraEnabled
        public String label {get; set;}
        @AuraEnabled
        public String value {get; set;}
    }
}